steps:
- name: 'docker/compose:1.28.2'
  args: ['up', '-d']
- name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'app:latest', 'gcr.io/tucshop/europe-central2-docker.pkg.dev/tucshop/tucshop-repo:$COMMIT_SHA']
images: ['gcr.io/tucshop/europe-central2-docker.pkg.dev/tucshop/tucshop-repo:$COMMIT_SHA']





