version: '3'

volumes:
  postgres_data:
    driver: local
  mongodb_data:
    driver: local
  mongodb_order_data:
    driver: local
  minio_data:
    driver: local

networks:
  default:
      driver: bridge

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3001:3000"
    environment:
      - MINIO_SERVER_ACCESS_KEY=IVMwKxXfI2snrUfQAS2d
      - MINIO_SERVER_SECRET_KEY=4zjPH7wpMeTzrqC3XE7goU592ZislS9SaGjaBQRB
    depends_on:
      - keycloak
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    

  postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    

  keycloak:
    image: quay.io/keycloak/keycloak:legacy
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: Pa55w0rd
    ports:
      - 8080:8080
    depends_on:
      - postgres
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    

  productsdb:
    image: mongo
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"

  mongodb-compass:
    image: mongo-express
    environment:
      ME_CONFIG_MONGODB_SERVER: productsdb
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: password
    ports:
      - "8082:8081"
    
  
  minio:
    image: 'bitnami/minio:latest'
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
    volumes:
      - minio_data:/bitnami/minio/data
    

  stripe-listen:
    image: stripe/stripe-cli:latest
    command: listen --forward-to=http://frontend:3000/api/stripe-webhook
    environment:
      STRIPE_SECRET: sk_test_51OU5hwJvUVrQpHMkIU7tDBk3WAxZjVw0bNMhuMPy9w1a6iB5V9MR6Cr1zUYLvTILHSmMh9P73ZPf20SpLexSlOtO00npckONT4
   

  product-service:
    build:
      context: ./product-service
    ports:
      - "3005:3005"
    depends_on:
      - productsdb
    environment:
      - MONGODB_URI=mongodb://productsdb:27017/test
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    

  ordersdb:
    image: mongo
    volumes:
      - mongodb_order_data:/data/db
    command: --port 27020
    ports:
      - "27020:27020"
   

  order-service:  # Add the new order service
    build:
      context: ./order-service
    ports:
      - "3007:3007"  # Choose a port that doesn't conflict with other services
    depends_on:
      - ordersdb  # Assuming ordersdb is the name of your MongoDB service
      - product-service
    environment:
      - MONGODB_URI=mongodb://ordersdb:27020/orders  # Update with your MongoDB connection string for orders
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    
    

  mongodb-compass-orders:
    image: mongo-express
    environment:
      ME_CONFIG_MONGODB_SERVER: ordersdb
      ME_CONFIG_MONGODB_PORT: 27020
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: password
    ports:
      - "8081:8081"
    





