version: '3'

volumes:
  postgres_data:
    driver: local
  mongodb_data:
    driver: local
  mongodb_order_data:
    driver: local
  minio_data:
    driver: local

networks:
  default:
      driver: bridge

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3001:3000"
    environment:
      - MINIO_SERVER_ACCESS_KEY=IVMwKxXfI2snrUfQAS2d
      - MINIO_SERVER_SECRET_KEY=4zjPH7wpMeTzrqC3XE7goU592ZislS9SaGjaBQRB
    depends_on:
      - keycloak
      - minio
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    

  postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    

  keycloak:
    image: quay.io/keycloak/keycloak:legacy
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: Pa55w0rd
    ports:
      - 8080:8080
    depends_on:
      - postgres
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    

  productsdb:
    image: mongo
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"

  mongodb-compass:
    image: mongo-express
    environment:
      ME_CONFIG_MONGODB_SERVER: productsdb
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: password
    ports:
      - "8082:8081"
    
  
  minio:
    image: 'bitnami/minio:latest'
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
    volumes:
      - minio_data:/bitnami/minio/data
    

  stripe-listen:
    image: stripe/stripe-cli:latest
    command: listen --forward-to=http://localhost:3000/api/webhook
    environment:
      STRIPE_SECRET: sk_test_51OU5hwJvUVrQpHMkIU7tDBk3WAxZjVw0bNMhuMPy9w1a6iB5V9MR6Cr1zUYLvTILHSmMh9P73ZPf20SpLexSlOtO00npckONT4
   

  product-service:
    build:
      context: ./product-service
    ports:
      - "3005:3005"
    depends_on:
      - productsdb
    environment:
      - MONGODB_URI=mongodb://productsdb:27017/test
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    

  ordersdb:
    image: mongo
    volumes:
      - mongodb_order_data:/data/db
    command: --port 27020
    ports:
      - "27020:27020"
   

  order-service:  # Add the new order service
    build:
      context: ./order-service
    ports:
      - "3007:3007"  # Choose a port that doesn't conflict with other services
    depends_on:
      - ordersdb  # Assuming ordersdb is the name of your MongoDB service
      - product-service
    environment:
      - MONGODB_URI=mongodb://ordersdb:27020/orders  # Update with your MongoDB connection string for orders
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    

  mongodb-compass-orders:
    image: mongo-express
    environment:
      ME_CONFIG_MONGODB_SERVER: ordersdb
      ME_CONFIG_MONGODB_PORT: 27020
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: password
    ports:
      - "8081:8081"
  

  zookeeper:
      image: confluentinc/cp-zookeeper:7.2.1
      container_name: zookeeper
      environment:
        ZOOKEEPER_CLIENT_PORT: 2181
      networks:
      - default

    
  kafka:
    image: confluentinc/cp-kafka:7.2.1
    container_name: kafka
    ports:
      - "8097:8097"
    depends_on:
      - zookeeper
      - order-service
      - product-service
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: EXTERNAL:PLAINTEXT,INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: EXTERNAL://172.17.0.1:8097,INTERNAL://kafka:19092
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost
    networks:
      - default
    restart: on-failure
    healthcheck:
        test: ["CMD", "ping", "-c","1", "172.17.0.1:8097"]
        interval: 30s
        timeout: 10s
        retries: 5
    extra_hosts:
      - "host.docker.internal:172.17.0.1"


  control-center:
      image: confluentinc/cp-enterprise-control-center:latest
      hostname: control-center
      depends_on:
        - kafka
      ports:
        - "9021:9021"
      expose:
        - 9021
      environment:
        CONTROL_CENTER_BOOTSTRAP_SERVERS: 'kafka:19092'
        CONTROL_CENTER_ZOOKEEPER_CONNECT: 'zookeeper:2181'
        CONTROL_CENTER_REPLICATION_FACTOR: 1
        PORT: 9021
      networks:
      - default
      restart: always
  




