version: '3'

volumes:
  postgres_data:
    driver: local
  mongodb_data:
    driver: local
  minio_data:
    driver: local

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3006:3006"
    environment:
      - MINIO_SERVER_ACCESS_KEY=IVMwKxXfI2snrUfQAS2d
      - MINIO_SERVER_SECRET_KEY=4zjPH7wpMeTzrqC3XE7goU592ZislS9SaGjaBQRB

  postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password

  keycloak:
    image: quay.io/keycloak/keycloak:legacy
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: Pa55w0rd
    ports:
      - 8080:8080
    depends_on:
      - postgres

  productsdb:
    image: mongo
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"

  mongodb-compass:
    image: mongo-express
    environment:
      ME_CONFIG_MONGODB_SERVER: productsdb
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: password
    ports:
      - "8081:8081"
  
  minio:
    image: 'bitnami/minio:latest'
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
    volumes:
      - minio_data:/bitnami/minio/data

  stripe-listen:
    image: stripe/stripe-cli:latest
    command: listen --forward-to=http://frontend:3000/api/stripe-webhook
    environment:
      STRIPE_SECRET: sk_test_51OU5hwJvUVrQpHMkIU7tDBk3WAxZjVw0bNMhuMPy9w1a6iB5V9MR6Cr1zUYLvTILHSmMh9P73ZPf20SpLexSlOtO00npckONT4
    
    


