services:
  keycloak_app:
    image: quay.io/keycloak/keycloak:22.0
    command: start-dev
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: postgres_keycloak
      KC_DB_URL_DATABASE: keycloak
      KC_DB_URL_PASSWORD: password
      KC_DB_USERNAME: keycloak
      KC_DB_SCHEMA: public
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8890:8080"
    depends_on:
      postgres_keycloak:
        condition: service_healthy
    networks:
      - keycloak_app_dev_network

  postgres_keycloak:
    image: postgres:14.2
    command: postgres -c 'max_connections=200'
    volumes:
      - pgdata_keycloak_app:/var/lib.postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USERNAME: keycloak
      POSTGRES_PASSWORD: password
      POSTGRES_HOST: keycloak
    healthcheck:
      test: "exit 0"
    ports:
      - "5436:5432"
    networks:
      - keycloak_app_dev_network
volumes:
  pgdata_keycloak_app:
networks:
  keycloak_app_dev_network:
    driver: bridge

